// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Fluent CQRS Framework")]
[assembly: AssemblyDescriptionAttribute("The next generation of CQRS Framework.")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright © Jan Fellien")]
[assembly: GuidAttribute("41246c8a-9b02-4be4-83ec-c88a26ee6054")]
[assembly: AssemblyProductAttribute("Fluent-CQRS")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
[assembly: InternalsVisibleTo("Fluent-CQRS.Domain")]

namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
